environment:
    type: "F_16env_trxl"
gamma: 0.99
lamda: 0.95
updates: 200  #20
epochs: 4
n_workers: 10
worker_steps: 101
n_mini_batch: 8
value_loss_coefficient: 1e-9
hidden_layer_size: 64
max_grad_norm: 0.5
transformer:
    num_blocks: 4
    embed_dim: 64
    num_heads: 1
    memory_length: 100
    positional_encoding: "relative" # options: "" "relative" "learned"
    layer_norm: "pre" # options: "" "pre" "post"
    gtrxl: True
    gtrxl_bias: 0.0
learning_rate_schedule:
    initial: 3.0e-4
    final: 3.0e-4
    power: 1.0
    max_decay_steps: 200 # anneal
beta_schedule:
    initial: 0.0
    final: 0.0
    power: 1.0
    max_decay_steps: 200
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 200